apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    app: project
    service: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
      service: project
  template:
    metadata:
      labels:
        app: project
        service: project
    spec:
      volumes:
      - name: project-volume
        persistentVolumeClaim:
          claimName: project
      containers:
      - name: project-container
        image: hhana982/project:1.<version>
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: project-volume
        env: 
        - name: DATABASE_HOST
          value: "project-db"
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "rootpw"
        - name: DATABASE_NAME
          value: "project"

